# Dogecoin Configuration Example for man-indexer-v2

protocolID = "6d6574616964"
module = ["mrc20"]
syncHost = ["*"]
blockedHost = []
cacheUrl = ""
syncDB = ""
adminToken = ""

[sync]
syncAllData = false
syncProtocols = []
syncBeginTime = ""
syncEndTime = ""
reSyncNum = 0
isFullNode = false
mrc20Only = true


[btc]
initialHeight = 844446
mrc20Height = 855888
rpcHost = "8.217.120.15:8332"
rpcUser = "dxshow63"
rpcPass = "sgOEs1pgEao5kL"
rpcHttpPostMode = true
rpcDisableTLS = true
zmqHost = "tcp://8.217.120.15:28333"
popCutNum = 21

# MVC Configuration
[mvc]
initialHeight = 86500
mrc20Height = 0
rpcHost = "127.0.0.1:9882"
rpcUser = "mvc"
rpcPass = "password"
zmqHost = "tcp://127.0.0.1:28882"
rpcHttpPostMode = true
rpcDisableTLS = true

popCutNum = 21

# Dogecoin Configuration
[doge]
#initialHeight = 6005461  # Set your initial block height
initialHeight = 6049343
mrc20Height = 6049343
# For Dogecoin Mainnet, use:
rpcHost = "8.217.234.33:23116"
rpcUser = "dxllzyll"
rpcPass = "kjgoep61xjg1i5u3"
rpcHttpPostMode = true
rpcDisableTLS = true
zmqHost = "tcp://8.217.234.33:15533"
popCutNum = 21

[pebble]
dir = "./man_base_data_pebble"
num = 2

[web]
port = "0.0.0.0:7777"
pemFile = ""
keyFile = ""
host = "localhost"

[metaSo]
pubkey = ""
prikey = ""
mongoNodeURI = ""
syncMode = ""
onlyHost = ""
feeRateHost = ""
feeLimit = 0
notifcationBlackedHost = []

[statistics]
metaChainHost = ""
allowHost = []
allowProtocols = []
