version = "0.2"
net = "mainnet"
protocolID = "6d6574616964"
module = ["metaname","mrc721","mrc20","metaso_notifcation"]
syncDB = "./sync_data.db"
adminToken = "metaid"
syncHost = ["*"]
[metaso]
feeRateHost = "http://47.238.91.186:8085"
feeLimit = 5
[sync]
syncAllData = true
syncBeginTime = ""
syncEndTime = ""
syncProtocols = ["payLike","simplerepost","paycomment"]
isFullNode = true
[statistics]
#metaChainHost = "http://127.0.0.1:7172"
metaChainHost = "http://47.238.186.172:7576"
allowHost = ["*"]
allowProtocols = ["*"]
[protocols]
  [protocols.payLike]
  fields = [{name = "isLike",class = "string",length = 1},
           {name = "likeTo",class = "string",length = 100}]
  indexes = [{fields = ["likeTo"],unique = false},
             {fields = ["pinId"],unique = true},
             {fields = ["pinNumber"],unique = false},
             {fields = ["pinAddress"],unique = false},
            ]
  key = "likeTo"
  [protocols.simplerepost]
  fields = [{name = "rePostComment",class = "string",length = 100},
           {name = "rePostTx",class = "string",length = 100},
           {name = "rePostProtocol",class = "string",length = 100}]
  indexes = [{fields = ["rePostTx"],unique = false},
             {fields = ["pinId"],unique = true},
             {fields = ["pinNumber"],unique = false},
             {fields = ["pinAddress"],unique = false},
            ]
  key = "rePostTx"
  [protocols.paycomment]
  fields = [{name = "content",class = "string",length = 100},
           {name = "commentTo",class = "string",length = 100},
           {name = "replyTo",class = "string",length = 100},
           {name = "pay",class = "string",length = 100},
           {name = "payTo",class = "string",length = 100}]
  indexes = [{fields = ["commentTo"],unique = false},
             {fields = ["pinId"],unique = true},
             {fields = ["pinNumber"],unique = false},
             {fields = ["pinAddress"],unique = false},
            ]
  key = "commentTo"
#regtest
[btc]
initialHeight = 100
mrc20Height = 0
rpcHost = "bitcoin-regtest.orb.local:18443"
rpcUser = "test"
rpcPass = "test"
rpcHttpPostMode = true
rpcDisableTLS = true
zmqHost = "tcp://bitcoin-regtest.orb.local:28333"
popCutNum = 0
[mvc]
#initialHeight = 91797
initialHeight = 145048
mrc20Height = 145048
#rpcHost = "192.168.1.30:9882"
rpcHost = "8.217.120.15:9882"
rpcUser = "showpay"
rpcPass = "showpay88.."
rpcHttpPostMode = true
rpcDisableTLS = true
zmqHost = "tcp://8.217.120.15:15555"
popCutNum = 21

[pebble]
dir = "./pebble_data"
num = 1
[web]
port = ":7777"
pemFile = ""
keyFile = ""
host = "https://man-test.metaid.io"